[tool.coverage.run]
branch = false
source = ["."]
omit = [
  "**/tests/*",
  "**/.venv/*",
  "**/.pytest_cache/*",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 100
exclude_also = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
]

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100